Fgts 203 polish all levels
fheysel/frogGoesToSpace pull request #103
Opened 2021-04-23 21:21 UTC by fheysel

Adds health bugs to game
Adds more birds to first level
Adds rats to second level
Fixes sawblade bug which causes it to collide with other sawblades, pushing them around the map

2021-04-23 21:27 UTC, charasyn requested changes
A few really minor changes

2021-04-23 21:27 UTC, charasyn commented on godotproject/Level0.tscn
> +position = Vector2( -4, 0 )
Was this changed intentionally? If not can you revert

2021-04-23 21:27 UTC, charasyn commented on godotproject/Tiles/Level2/Computer.png.import
> +flags/filter=true
```suggestion
flags/filter=false
```

2021-04-24 18:00 UTC, fheysel commented
Approved by @charasyn

2021-04-24 18:01 UTC, merged