Fgts 119 create rat enemy
fheysel/frogGoesToSpace pull request #45
Opened 2021-02-01 06:14 UTC by jDenyes

Added the enemy rat in

2021-02-01 17:57 UTC, fheysel commented
I pulled the branch and put sent some comments in the Teams chat along with a video but I'll post them here too for reference. 

The rat enemy is looking good but there are still a few things that need to change before its demo ready. The first is that we still need to jump into frame for the enemy to see us. The second is that even when you jump into frame you have to be standing very close to get seen by the rat, the raycasts can be extended so that his jump ends right at the player. The last thing is that the hit box is too large. When you watch the video you can see that the player dies far before the rat ever actually touches them. It would be pretty frustrating from a players pov

2021-02-04 03:15 UTC, charasyn requested changes

2021-02-04 03:15 UTC, charasyn commented on godotproject/rat_spritesheet.png.import
> +path="res://.import/rat_spritesheet.png-0ef4b8f8dd66edc1ec1cb2e54751a5e7.stex"
Git seems to have marked this as replacing the `birds.png.import` file, which I don't think is correct and will probably break the bird. Pls give it another check as to whether this is intended and whether everything still works

2021-03-29 21:09 UTC, fheysel commented
This looks good for the most part, I pulled it and played but there are a few small thing. 1 lower the rats z index so the player is always in front. 2. rat attack deals 0 damage atm, increase that. 3. Something is printing a lot to std out, remove print statements. 4. The rat should have sound effects for when it sees the player and then when it attacks, something like a growl and then a slash sound or something. Check out https://freesound.org/ thats where we've been getting all our sound effects from.

2021-03-30 01:58 UTC, fheysel commented
The rat also does not take damage

2021-04-20 14:37 UTC, fheysel approved these changes
Changes look great! I love the sound effects you chose :)

2021-04-23 19:43 UTC, charasyn approved these changes

2021-04-23 19:44 UTC, charasyn requested changes
Wait hold on

2021-04-23 19:44 UTC, merged