Fgts 81 enemy takes damage from player tongue
fheysel/frogGoesToSpace pull request #47
Opened 2021-02-01 17:24 UTC by jDenyes

added in functionality for tongue to damage "ant" enemies. This functionality will be built upon for collectable objects like the star and the flies / other enemies

2021-02-01 18:07 UTC, fheysel commented
We need some kind of sound/visual indication that the enemy has taken damage and an animation for its death so that it doesnt just disappear. This might have to wait until the next demo.

2021-02-01 20:06 UTC, jDenyes commented
I'd rather include this functionality for now without death animations then not include it all.

2021-02-01 20:56 UTC, fheysel commented
the stars arent tongueable when I play on this branch

2021-02-02 17:48 UTC, jDenyes commented
@fheysel Stars shouldn't be tongueable on this branch.

2021-02-02 21:30 UTC, charasyn requested changes
Here are a few style changes:
- We should have tongue damage and health be 1 and 2, instead of 50 and 100
- Align text using spaces instead of tabs

2021-02-02 21:30 UTC, charasyn commented on godotproject/PlayerTongue.gd
> +
```suggestion
const COLLISION_LAYER_TONGUEABLE        = 0x3
const COLLISION_LAYER_TONGUE_CAN_DAMAGE = 0x6

```

2021-02-02 21:30 UTC, charasyn commented on godotproject/PlayerTongue.gd
> +
```suggestion
var tongue_damage = 1

```

2021-02-02 21:30 UTC, charasyn commented on godotproject/enemy-Ant.gd
> +var health = 100
```suggestion
var health = 2
```

2021-02-02 21:31 UTC, charasyn approved these changes

2021-02-02 21:32 UTC, merged