Added Circular Saw Blade
fheysel/frogGoesToSpace pull request #75
Opened 2021-03-14 21:58 UTC by jDenyes

2021-03-16 16:16 UTC, charasyn requested changes
Hey, there are a few things that I think should be cleaned up before being checked in. In addition, I think the files should be moved into a folder. As per teams, I'll move it and change the image size

2021-03-16 16:16 UTC, charasyn commented on godotproject/SawBlade.gd
> +	pass
```suggestion

# In order to stop the tongue when it hits the sawblade, we have our "tongue_can_damage" collision bit set.
# However, the saw shouldn't take damage from the tongue, so we have this empty function.
func take_damage(damage):
	pass
```

2021-03-16 16:16 UTC, charasyn commented on godotproject/SawBlade.gd
> +
```suggestion
```

2021-03-16 16:16 UTC, charasyn commented on godotproject/SawBlade.gd
> +#	var collNode = get_node("PlayerCollision/CollisionShape2D")
```suggestion
```

2021-03-16 16:16 UTC, charasyn commented on godotproject/SawBladeArea.gd
> +#	pass
Can you remove this unused script?

2021-03-16 16:16 UTC, charasyn commented on godotproject/SawBladeArea.tscn
> +
I don't see the timer used anywhere in the code.. can it be removed?

2021-03-16 17:16 UTC, charasyn reviewed
Updated with all the changes I asked for - no functional changes, just some cleanup and resizing of the sprite. Can someone double-check

2021-03-16 22:22 UTC, charasyn approved these changes

2021-03-17 20:13 UTC, charasyn commented
Uh oh. I think there are two copies of the sawblade now. I think I probably shouldn't have force pushed...

2021-03-19 02:16 UTC, fheysel commented
There are 2 tscn and gd files for the sawblade. Need to resolve and delete one of them before we can merge

2021-03-19 15:55 UTC, fheysel commented
@jDenyes  or @charasyn could one of you resolve the duplication so we can merge this please?

2021-03-19 16:24 UTC, charasyn commented
Okay I force pushed again without squashing the commits this time. The branch should be in a good state so it should be ready to merge.

2021-03-19 16:29 UTC, charasyn commented
Wait this doesn't have Jacob's changes that he was working on to change how the sawblade moves. I'll message him to sort it out

2021-03-19 21:01 UTC, jDenyes commented
adding audio file as Fiona suggested, waiting for conversion from mp3 to godot supported format.

2021-03-19 22:27 UTC, charasyn requested changes
After talking with Jacob, I'm making some modifications locally to fix some things

2021-03-20 13:50 UTC, charasyn approved these changes
OK I added my changes. @jDenyes can you please look over the commit that I made and approve it? If it's ok with you then it should be good to merge.

2021-03-20 14:07 UTC, jDenyes commented
@charasyn thanks for the cleanup. I actually encountered a bug while testing rn so I'm gonna fix it quickly. framerate drops lead to weird behavior.

2021-03-20 14:09 UTC, charasyn commented
Make sure you pull this and check to make sure it's still there. I actually have FPS drops when running the game in-editor so I moved the code from _process to _physics_process

2021-03-20 14:15 UTC, jDenyes commented
What's the difference between the two?

2021-03-20 14:16 UTC, jDenyes commented
It actually looks good now, but it's hard to reproduce. Sometimes the sawblade would just yeet to infinity, but looking at the logic it's hard for me to understand why.

2021-03-20 14:29 UTC, charasyn commented
In _physics_process the delta is always the same, there's always 60 physics process per second
________________________________
From: jDenyes ***@***.***>
Sent: Saturday, March 20, 2021 10:16:21 AM
To: fheysel/frogGoesToSpace ***@***.***>
Cc: Cooper Harasyn ***@***.***>; Mention ***@***.***>
Subject: Re: [fheysel/frogGoesToSpace] Added Circular Saw Blade (#75)


It actually looks good now, but it's hard to reproduce. Sometimes the sawblade would just yeet to infinity, but looking at the logic it's hard for me to understand why.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/fheysel/frogGoesToSpace/pull/75#issuecomment-803358019>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABOYR5IDU2LUKOSROURCYWLTESU3LANCNFSM4ZFNGDUQ>.

2021-03-20 15:17 UTC, jDenyes commented
Ok with those changes I'm happy to merge to main. @fheysel to set the spawn point edit the StartPos, to change where it goes to edit the EndPos. Come work with me to integrate. I'm putting it in now

2021-03-20 15:21 UTC, merged